version: '3.8'

services:
    php:
        build:
            context: ./docker/php
        container_name: symfony_php
        ports:
            - '9456:9000'
        working_dir: ${WORKING_DIR}
        volumes:
            - ${PROJECT_DIR}:${WORKING_DIR}

    nginx:
        image: nginx:stable-alpine
        container_name: symfony_nginx
        ports:
            - '8080:80'
        volumes:
            - ${PROJECT_DIR}:${WORKING_DIR}
            - ${PROJECT_DIR}/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
